### ISSUE TITLE
German menu should link to english blog with notification

### ISSUE THREAD

**Issue by feedm3** [satellytes/satellytes.com#110]
We want to remove the german blog overview and link directly to the english blog. 

This can confuse the user, as all links on the page (for example in the menu) will link to english sites. To reduce the confusion, a notification to the user is shown on the overview page. The notification informs the user about the language change.

**Comment by georgiee** [comment]
Do we really want that? 
I don't want to introduce a notification system/dialog purely for this purpose.

As described already it's confusing. Instead of "fixing" the confusion why not keep the great & simple solution to tell the user about the blog being not available in German?

**Comment by fischeversenker** [comment]
If I understand correctly this issue is meant to be a follow up issue **after we removed the "german blog overview" page**? But why would we want to remove this page? I really like the flow and I don't think it makes sense to remove that German interim page.
If we simply keep it we don't need to come up with some notification mechanism that might be overlooked by the users. What's wrong with the current approach?

**Comment by feedm3** [comment]
This was an early idea from design so I kept it as an issue to think about. As the current flow with the german blog overview page works quite well I will close this issue.
