### ISSUE TITLE
Component: TextHighlight ContentBlock

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#176]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3713%3A18327

**Comment by georgiee** [comment]
Oh that's lovely and something I always wanted to have for blog posts to provide some highlighted text, like you can do it easily in notion with the `call outs`. That's probably also the name I would like to use for this component.

That's the component in Notion for comparison:
https://www.notion.so/Callout-blocks-5b2638247b54447eb2e21145f9

![Screen Shot 2021-11-11 at 17 39 03](https://user-images.githubusercontent.com/1701755/141335270-ee2a70b0-52b0-42b5-bcfc-77d49ba46eda.png)

**Comment by georgiee** [comment]
That helped me to get the necessary svg loading working:
https://github.com/storybookjs/storybook/issues/12963

I had problems with the rule update mostly because my TypeScript definition for the svg content was wrong (and therefore undefine). Now it looks good and I can focus on completing this component.
