### ISSUE TITLE
Component: Quote ContentBlock

### ISSUE THREAD

**Issue by fischeversenker** [satellytes/satellytes.com#177]
### Design
https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3701%3A23643

**Comment by georgiee** [comment]
I think we need a cite source optionally too have such a quote content block.
See this reference https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

I see myself using it once we have it and I think the design team aligned the design more on the status quo that's why it's missing. I'm going to propose it.

![Screen Shot 2021-11-25 at 17 00 01](https://user-images.githubusercontent.com/1701755/143472550-10628b32-17ca-45ac-8524-3697a11c7203.png)


Good for now though👍
