### ISSUE TITLE
Open blog post images in lightbox

### ISSUE THREAD

**Issue by erdoesa** [satellytes/satellytes.com#323]
From UX point of view I would suggest to open blog post images in a lightbox instead of new browser tab.

**Comment by georgiee** [comment]
The current behavior is "link to the original source of the image" in a new window (`_blank`, new window/tab) which adds the possibility to inspect an image in bigger size if it feels relevant to you. We don't have any grouped images (galleries) nor are usually crucial for a blog post. They are more than a decoration but usually less than a crucial part. That's why I'm so confused that you came to that feature idea.

I wonder what you drove to make that requirement. Was there a real pain you felt? What do you want to achieve? Display all images of a blog post in a gallery? Display an image in a bigger size ? 

Here a few points that came to me immediately:

1. Modals need JavaScript and bring additional complexity which need to be out weight by the purpose which I'm missing here. What does the user win exactly without being too generic like "better UX". Tell me what you see that I can't see.

2. Modals interrupt me as the user. 
I'm looking at a blog post. I'm reading mostly text with a few images. There is no point of grouping together the few images because they don't belong together- so the gallery aspect is directly irrelevant. 

What's left, the bigger image size? That was definitely not the intention in mind when I added the few images. The images are meant to loosely visualize what the text is about. If folks want to further inspect details of the image they can optionally click the image and do whatever the browser gives you to zoom in to images opened in a tab. We are using a native, very old and very known feature of a browser that an image opens directly in the browser. You are not forced to click. If you think there is more content hidden I think we can improve the current UX by stating that you can click the image for a higher resolution. Or we can discuss the fact if it should open in a new tab or current tab.

3. Modals don't work on mobile devices. 
They are just pointless as you don't have the additional screen estate.

4. Touch enabled devices: Pinch and Zoom.
People can use that gesture on many mobile devices if the want to inspect an image loaded in the browser. Good luck exposing that feature in a lightbox without adding even more complexity

5. Accessibility.
The modal window of a lightbox creates an additional layer of content. Something that happens on our website nowhere else. That additional layer usually blocks the underlying content visually. You always need an extra step back to the content by closing the additional layer. You mentioned before in a chat that you don't like the extra step of closing the new tab. I wonder why you would accept that extra step of closing a lightbox window. It's virtually the same count of interactions but worse as you distract the user by showing a fraction of the original content underneath the layer.

Actually I think the open layer is even worse. When I [read some details](https://www.nngroup.com/articles/modal-nonmodal-dialog/) at my trusted UX resource Norman Group they list that exact part:

> They cause the users to create and address an extra goal — to dismiss the dialog. When the dialog is presented, extra steps are added to the user’s workflow: to read and comprehend the dialog, then make a decision on that dialog. This increase in interaction cost is likely to put off users, unless the dialog is well justified and indeed contains important information. We will elaborate more on this point later.

And I feel that. That extra goal, I can feel it while the extra window open for an image is less distracting and much more natural as you are navigating all the day.

6. Routing
How would you route the additional content displayed on the website? Because what ever you display to the user should be directly accessible to the user. Will you create crippled urls with anchors that you misuse to open the lightbox when that specific url is opened? Will you create real urls with pushstate? How will you handle the server-side rendering of such links? Modals really don't integrate well into the routing & navigation practice or browser. They never did and it was a pain the ass since forever.

7. Another one from Normal group that resonates pretty good with me:
> They cause users to forget what they were doing. Once the context is switched to a different task, because of the additional cognitive load imposed by the modal dialog, people may forget some of the details associated with the original task. If that is the case, recovering context for the original task may be even more difficult.

This is about **cognitive load** which is something I cite a lot when talking about interactions that get too complex for users. I can fell that cognitive load again just by imaging I interact with a lightbox. I click on an image, the entire page is changing because it's fading to black, I see additional dialogs as I have to interact with the extra content layer. Just do look at a slightly bigger image. This feels just wrong.

8. Animation
Don't get me started with that one. I have touched so many modal dialogs that were animating the background first and the slowly showed the content. This just robs me tons of time when I compare that with my usually speed interaction time.

9. New Layer, New Interaction Concept
So we open a new layer. Now the user has to learn a new concept. There is a closing window. Maybe the background can be clicked. Maybe I can just scroll to close it. Maybe nothing of that matches the expectations of the user? So many decisions and things to learn by the user just to see the details of the clicked image.

---

That's quite a lot. I forced myself to think about the good parts for our case but I can't find any scenario that would speak for the lightbox. Maybe you can help?

A lightbox or better the modal window is good for attention grabbing. Some error, some dialog that needs immediate response. I'm fine with that, but not for such a simple thing as an image. I love to rely on the most basic functionalities of browsers and open an image in a new tab is exactly that. Nothing can go wrong, the user will always understand what's happening/


Where to go from here? Should we improve the way the image is linked and ditch the lightbox idea? Or can you present some valid facts that make the lightbox indispensable for our blog and not just a matter of your personal taste?

Thanks for igniting that discussion 💫

**Comment by fischeversenker** [comment]
I'd very much like to disagree with a lot of the things you wrote, @georgiee. It seems like you are projecting a lot of your own knowledge about browsers onto the average user. Both of your NN Group quotes are irrelevant in my opinion. They both deal with more complex modal dialogs that include forms (or at least text) and most importantly they don't compare the UX of opening a dialog vs. opening a new tab. As far as I can tell they compare the UX of opening a dialog vs. navigating to a separate page in the same tab - or, for desktop applications - vs. opening a separate window. Dialog != Ligthbox.

I strongly believe opening a Lightbox for a single image results in better UX than opening a new tab.

### Closing the image
The main reason why I'd prefer a modal is that closing a modal is easier than closing a tab. In web design "intuitive" is a synonym for "familiar" and a modal is a very well known concept and users know how to interact with it. Most important to me is "Fitt's Law":
To close a tab you either click on the X on the browser tab or you press Ctrl+w/Cmd+w or you middle-click on the tab. To close a modal you click anywhere outside (maybe even inside) of the modal or you press Esc.. The effort to close a modal is less than the effort required to close a new tab. In all dimensions. Less required mouse movement, bigger clickable area, less keys to press.

### Context switch
You (Georgios, and most developers) are perfectly aware of your browser tabs. You instantly realize that a new tab was opened. You know where the old tab is and how to navigate back to it (by either closing the new tab or switching to the old one). That is certainly not true for all users. My mom would be absolutely clueless what just happened. She would probably panic, close the entire browser and would have no idea how to get back to the blog. To be fair, my mom is probably not our average user, but you can't assume the same level of techy-ness from our users as you have. Medium solves this very elegantly with a very lightweight Lightbox that (using animations and a backdrop) helps the user to understand that the image is just being zoomed in ([Example article](https://newanddigital.medium.com/from-memes-to-menace-revisiting-copium-memes-a-year-later-6c7b2cdc42ff) with two images). The user intuitively understands that he is still on the same page. No context switch, no flicker, just elegance. "Closing" the image is done by just clicking again. Anywhere.

### Resources
- Random article about lightboxes: https://www.motocms.com/blog/en/lightbox-design-for-ux/
- Fitt's Law: https://de.wikipedia.org/wiki/Fitts%E2%80%99_Gesetz
- Medium article with images: https://newanddigital.medium.com/from-memes-to-menace-revisiting-copium-memes-a-year-later-6c7b2cdc42ff
- Dev.to article with images: https://dev.to/devdefinitive/30-javascript-libraries-to-use-in-your-projects-1gd3 (images open in same tab. Worst UX imho)
- NNGroup on how to avoid misusing Overlays/Lightboxes/Modals: https://www.nngroup.com/articles/overuse-of-overlays/
- "Intuitive equals familiar": https://www.asktog.com/papers/raskinintuit.html

---

All in all I just wanted to express my discomfort with "It's easier to close a tab than it is to close a modal" since I claim this is by far not true for most users. Regardless of all these arguments and regardless of whether a modal or a tab is the better approach, **I suggest we completely disable this functionality.** Images in blog posts should just serve as decoration and not contain any additional information. By not making them clickable we avoid this problem once and for all.

**Comment by georgiee** [comment]
Thanks @fischeversenker for your comment and surprisingly I think I can agree now. The moment you mentioned medium it clicked for me. I always had a clunky, gallery with slow transitions in mind. Of course I thought about some more lightweight variant but an example would have helped to talk about. I think the lack of explaining exactly what Arthur wants minus the missing examples confused me a lot and strengthened my dislike.

In all those discussions we forget: Only tech savvy people will read our blog and even if someone finds our blog, opening the images will be not of their concern while being confused about the stuff we are writing 😁

I'm happy and ready for such a feature 👍 Medium is a great example, here one [example article](https://cryptohayes.medium.com/maelstrom-ee6021e9d0c2) for your convenience.

**Comment by erdoesa** [comment]
I like this debate and would appreciate disabling image click for now. 
But would love to see medium style behaviour in near future as well! Zooming images makes definitely sense sometimes.

**Comment by georgiee** [comment]
I will close this issue and create an actionable issue. Thanks for the great discussion👍
