### ISSUE TITLE
Introduce Blog Pagination

### ISSUE THREAD

**Issue by georgiee** [satellytes/satellytes.com#533]
Our blog is growing and growing and with the introduction of a CMS I think it's a good time to start thinking of a pagination to split the content in multiple pages. There are some resources available for Gatsby and I'm sure they help to get us running. 

1. This will involve adapting the contentful GraphQL query, providing a new component on the different blog pages and have a page query or path segment to hold the information. 
2. In addition we should think about SEO, do we need anything because of the changing page content? Changing or updated page dates (which @milljoniaer mentioned anyway in another issue about SEO, can't find the related issue though)
3. I think of 10-20 blog articles per page. No need to provide a filter or different page size configurations. We anticipate a change of the blog towards a "news outlet" in the future to hold more content (besides blog), so we will talk about filtering content at that time I guess. Let's keep things simple.

One related topic is the actual design. We have an initial pagination component provided through (#191) but I think we should see if that works with the actual implementation. Nonetheless we should pick that to get things running.

Resources:
+ https://www.gatsbyjs.com/docs/adding-pagination/
+ https://github.com/satellytes/satellytes.com/pull/191

**Comment by feedm3** [comment]
One idea that came to my mind: Instead of pagination just add a "Load more" button that would show the next X teasers. 

**Pros:**
- Simpler routing. Only one page is necessary to handle everything
- If we get the teasers somehow dynamically, we can extend the page functionality also with filters and a search (Cloudinary has search build in)
- It scales to infinity ♾️ 

**Cons:**
- We need to find a way how to get the teasers to the frontend. Could be done by directly fetching the data from the Contentful API (maybe with a Gatsby Cloud function as proxy if auth tokens are required).
- What makes this dynamic approach particularly difficult is the `GatsbyImage` we use as a teaser image. This needs a specific data format, as well as pre-generated images. This doesn't work with SSR or dynamic data. We probably need to drop this component and replace it with a classic `<img />`, which shouldn't be a big deal if we can make sure we have the images in a correct format (width and height is known before and doesn't really change).

**Comment by georgiee** [comment]
I love the simplicity of the pagination and I have never imagined a load more button.

My main issue with the `load more` button is usability: Reloading & Navigation forth and back puts me usually on the start page again or needs some fancy technology to fetch everything again and auto scroll. This is super annoying because it takes quite some time and takes over the scrolling which is for me a no-go.  You also need a click so why not spend the click on a "next page" button and give the user the classical, learned and technical simple functionality.

To address your pros, because I don't agree with them:
+ Simpler routing is not issues for us, I think we should be able to create the few pages and derive a pagination.
+ We don't need filters for quite some time. I outlined that explicitly before.
+ We don't need infinity for our small blog yet 😄

I agree with your cons but they are super technical issues that you could phrase as a technical challenge. I have far more issues with the usability impact 🙏 I hope this doesn't sound rejecting without thinking because I really tried to imagine such a button but I think pagination would be the best solution right now for our amount of blog posts.
