### ISSUE TITLE
Page preview image not showing on LinkedIn/Twitter

### ISSUE THREAD

**Issue by esreverse** [satellytes/satellytes.com#635]
https://satellytes.com/career/senior-frontend-engineer/
https://satellytes.com/career/frontend-engineer/

![CleanShot 2022-06-01 at 13 00 00](https://user-images.githubusercontent.com/6918281/171389684-abb945cc-4f55-471f-b6bc-21776f50b6fa.png)

**Comment by georgiee** [comment]
The best tool to check if something is technically wrong in case of linkedin is https://www.linkedin.com/post-inspector/inspect/. Another more general tool is metatags.io/

The funny thing what happened here. I could confirm your issues by trying to share those links. Then I checked on metatags but everything was reported as okay. Still sharing did not work. Then I checked with the post inspector and it showed that everything is okay. Suddenly a share of the urls worked. Go on and check for yourself, it's fixed.

Might have been some caching issue on LinkedIn side. We should did deeper once this happen again because then LinkedIn might have some problems the way Gatsby deploys updates of images or so.

**Comment by esreverse** [comment]
https://satellytes.com/career/senior-ux-ui-designer/ I tried to post this to my LinkedIn. No preview again. Checked Post-Inspector: Showing errors. Can someone check and in case fix it?

**Comment by feedm3** [comment]
Post inspector works for me: 
<img width="1176" alt="grafik" src="https://user-images.githubusercontent.com/7814926/173603461-8534fa35-1d62-4a60-a5e1-7dd5bda492b5.png">

It also works on LinkedIn:
<img width="595" alt="grafik" src="https://user-images.githubusercontent.com/7814926/173603569-cd05f2b7-ac0b-4cc1-a0ae-261d79f19f33.png">

**Comment by esreverse** [comment]
Awesome. Tried it 4 times. Didn't work. Just tried again. Worked. Same browser. Weird 10000. Thanks for looking/helping. 🙂
