### ISSUE TITLE
Sr. Software Engineer not found (on the german side)

### ISSUE THREAD

**Issue by abdolg** [satellytes/satellytes.com#766]
In the German translation, the position of Sr. Software Developer has disappeared. The url https://satellytes.com/de/career/senior-software-engineer/ shows the wrong content. 

![Bildschirmfoto 2023-08-21 um 10 27 00](https://github.com/satellytes/satellytes.com/assets/13379786/744f300a-ccc0-4dfb-8d08-972314d7abeb)

**Comment by WiebkeFr** [comment]
I corrected the title and description of the german page for [Sr. Software Developer](https://satellytes.com/de/career/senior-software-engineer/) on [Contentful](https://app.contentful.com/spaces/54dnxp2417nl/entries/2ZKOua9zGgt9ltrw6D2LXf).
The issue is now resolved. -> https://satellytes.com/de/career/senior-software-engineer/
